#!/usr/bin/env bash

systemctl disable --now uit-api

uitServerdDir="/tmp/uit-serverd"
uitAPIDir="/tmp/uit-api"
uitWebDir="/tmp/uit-web"
uitClientDir="/tmp/uit-client"

function cleanup() {
	if [[ -d "$uitAPIDir" ]]; then
		rm -rf "$uitAPIDir"
	fi
	if [[ -d "$uitWebDir" ]]; then
		rm -rf "$uitWebDir"
	fi
	if [[ -d "$uitClientDir" ]]; then
		rm -rf "$uitClientDir"
	fi
	if [[ -d "$uitServerdDir" ]]; then
		rm -rf "$uitServerdDir"
	fi
}

trap cleanup EXIT

if [[ "$EUID" > 0 ]]; then 
  echo "Please run as root. Exiting..."
  exit 0
fi

downloadFromGithub="$1"

if [[ -z $downloadFromGithub ]]; then
	read -p "Download from GitHub? [Y/n]: " downloadFromGithub
fi

function tryGithubDownload() {
	local repoName="$1"
	local destDir="$2"
	rm -rf "$destDir"
	echo "Downloading $repoName from GitHub..."
	git clone "https://github.com/cameronraschke/${repoName}" "$destDir"
	gitStatus=$?
	local i=10
	while [ "$gitStatus" -ne 0 ] && [ "$i" -gt 0 ]; do
		echo "Download failed, retrying..."
		sleep 1
		rm -rf "$destDir"
		git clone "https://github.com/cameronraschke/${repoName}" "$destDir"
		gitStatus=$?
		((i--))
	done
	if [[ "$gitStatus" -ne 0 ]]; then
		echo "Download of '${repoName}' failed after ${i} attempts. Exiting..."
		exit 1
	fi
}

function installPackage() {
	local packageDir="$1"
	local packageName="$2"
	if [[ -z $packageDir || -z $packageName ]]; then
		echo "installPackage() requires two arguments: packageDir and packageName. Exiting..."
		exit 1
	fi

	if [[ -n $(dpkg -s $packageName 2>/dev/null) ]]; then
		if [[ $packageName == "uit-client" ]]; then
			# No important data, can purge
			dpkg --purge uit-client
		else
			dpkg --remove remove "$packageName"
		fi
	fi

	if [[ -d "$packageDir" ]]; then
		(
			cd "$packageDir"
			chmod 755 "$packageDir/DEBIAN"
			chmod 755 "$packageDir/DEBIAN/control"
			chmod 755 "$packageDir/DEBIAN/postinst"
			dpkg-deb --build --root-owner-group "$packageDir"
		)
		packagePath="$packageDir.deb"
		if [[ -f "$packagePath" ]]; then
			echo "Installing package '$packageName' from '$packagePath'..."
			if [[ $packageName == "uit-client" ]]; then
				mv -v "$packagePath" /srv/uit-toolbox/client/pkg/uit-toolbox-client.deb
			else
				dpkg --install "$packagePath"
			fi
		else
			echo "Package '$packageName' not found at '$packagePath'. Exiting..."
			exit 1
		fi
	fi
}

if [[ -z $downloadFromGithub || $downloadFromGithub == "y" || $downloadFromGithub == "Y" ]]; then
  rm -r /tmp/uit-toolbox/
  tryGithubDownload "uit-api" "$uitAPIDir"
	tryGithubDownload "uit-client" "$uitClientDir"
	tryGithubDownload "uit-serverd" "$uitServerdDir"
	tryGithubDownload "uit-web" "$uitWebDir"
  echo "Download complete."
else 
  echo "Not downloading."
fi

# installPackage skips installation of client package on server
installPackage "$uitAPIDir/uit-api_1.0-1_amd64" "uit-api"
installPackage "$uitClientDir/uit-client_2.0-1_amd64" "uit-client"
installPackage "$uitWebDir/uit-web_1.0-1_amd64" "uit-web"
# Server has to be last because it depends on the other packages being installed first
installPackage "$uitServerdDir/uit-serverd_1.0-1_amd64" "uit-serverd"


## Create Golang binaries
# Server daemon (uit-api) managed by systemd, compilation in postinst script. Daemon NOT started until end of this script.
# Client daemon & CLI
rm /srv/uit-toolbox/client/pkg/uit-clientd
(cd ${uitClientDir}/uit-client_2.0-1_amd64/opt/uit-toolbox/uit-clientd/
	sudo /usr/local/go/bin/go build -buildvcs=false -o /srv/uit-toolbox/client/pkg/uit-clientd .
	sudo /usr/local/go/bin/go build -buildvcs=false -o /srv/uit-toolbox/client/pkg/uit-cli ./cmd/uit-cli
)

systemctl daemon-reload
systemctl enable --now uit-api